spring:
  application:
    name: client

server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers

resilience4j:
  circuitbreaker:
    instances:
      slowService:
        register-health-indicator: true
        # Look at the last x calls
        sliding-window-size: ${SLIDING_WINDOW_SIZE:5}
        # At least x calls must be made to evaluate
        minimum-number-of-calls: ${MINIMUM_NUMBER_OF_CALLS:3}
        # x% failure rate to trip the circuit breaker
        failure-rate-threshold: ${FAILURE_RATE_THRESHOLD:50}
        # Stay OPEN for x seconds
        wait-duration-in-open-state: ${WAIT_DURATION_IN_OPEN_STATE:10s}
        # Allow x calls in HALF_OPEN state
        permitted-number-of-calls-in-half-open-state: ${PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE:2}
        automatic-transition-from-open-to-half-open-enabled: true
